### ISSUE TITLE
App Screenshot

### ISSUE THREAD

**Issue by JoseCage** [braulio94/Brhymes#4]
Yo @braulio94 can you include a sreenshot of your app in **`README`** file?

**Comment by braulio94** [comment]
@JoseCage  no I can't. because this app is not finished. I plan to do finish it, you can watch the repo.

**Comment by JoseCage** [comment]
>  I can't. because this app is not finished.

Ok. Can't you make a screenshot of a dev version? I mean, from the point you are at this moment.

**Comment by braulio94** [comment]
trust me you don't want to see a blank screen.. 😄

**Comment by JoseCage** [comment]
> trust me you don't want to see a blank screen...

😄 😄 😭 now I understand. Well, I'll wait.

Let me know please when you release the app.

**Comment by braulio94** [comment]
yeah sure

**Comment by JoseCage** [comment]
2 months later. No news @braulio94 ?

Yeah, I know you are busy these days, but **give me news please**.

### **Finish the challenge** 🥇

**Comment by braulio94** [comment]
## Yes, Boss! 👨‍💻

**Comment by JoseCage** [comment]
> Yes, Boss! 👨‍💻

Enjoy partner. 😄

**Comment by JoseCage** [comment]
After 3\4 months. @braulio94 Do we have news of your app?

If you cant finish the app I think I need to remove from [umappem24h](https://github.com/JoseCage/umappem24h) repo.

I really appreciate your participation but the rule is to finish the project.

**Comment by braulio94** [comment]
I don't mind. I don't know how long it's going to take.

**Comment by JoseCage** [comment]
> I don't mind. I don't know how long it's going to take.

Okay, I understand. Let me know when/if you finish.
